name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Prueba de tarea
      id: prueba-de-tarea
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Prueba de tarea
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRUEBA-DE-TAREA_RESULTS: "${{steps.prueba-de-tarea.outputs.result}}"
      with:
        runners: prueba-de-tarea
